---
kind: Service
apiVersion: v1
metadata:
  name: keycloak
  namespace: logging
  labels:
    app: keycloak
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:198814579854:certificate/9d76f3fd-330c-48c8-a0dc-cae8febb783f
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerSourceRanges:
    - 15.0.0.0/9
    - 192.56.0.0/16
    - 76.126.85.105/32
  selector:
    app: keycloak
  ports:
#  - name: http
#    port: 8080
#    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8080