# kibanaserver: aJI9Kca6OjnuCjMAJXNKXw  hash: $2y$12$wfIBsxpMkp5UitbzNerMNuuL46teKY48coWb29lIQblIR2e2VAH7.
# Admin: qDL5GbHcT8pm0QIRD2Y6A hash: $2y$12$hFW93d5Wcpi7cQ0M9T3hheA3iWQzfL7/FwE4ETEiJRVsnGZXrB0gm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
data:
  kibana.yml: |-
    ---
    # Default Kibana configuration from kibana-docker.
    server.name: kbna-dev.hpbp.io
    server.host: "0"
    logging.verbose: true

    # Replace with Elasticsearch DNS name picked during Service deployment
    elasticsearch.hosts: https://elasticsearch:9200
    elasticsearch.requestTimeout: 360000
    elasticsearch.ssl.verificationMode: none
    elasticsearch.username: kibanaserver
    elasticsearch.password: aJI9Kca6OjnuCjMAJXNKXw
    elasticsearch.requestHeadersWhitelist: ["securitytenant","Authorization", "security_tenant", "x-forwarded-for", "x-forwarded-by"]

    opendistro_security.multitenancy.enabled: true
    opendistro_security.multitenancy.tenants.preferred: ["Private", "Global"]
    opendistro_security.readonly_mode.roles: ["kibana_read_only"]
    opendistro_security.cookie.secure: true
    opendistro_security.cookie.password: “12345678901234567890123456789012”

    # Enable OpenID authentication
    opendistro_security.auth.type: "openid"
    opendistro_security.openid.scope: "openid profile email"

    # The IdP metadata endpoint
    opendistro_security.openid.connect_url: "https://key-dev.hpbp.io/auth/realms/kibana/.well-known/openid-configuration"
    # The ID of the OpenID Connect client
    opendistro_security.openid.client_id: "kibana-sso"

    # The client secret of the OpenID Connect client
    opendistro_security.openid.client_secret: "69f1e74e-03b5-4e50-9ac9-7a42930a32f7"

    opendistro_security.openid.base_redirect_url: "https://kbna-dev.hpbp.io/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
  labels:
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
     component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      containers:
      - name: kibana
        # Official Image from Open Distro Team
        image: amazon/opendistro-for-elasticsearch-kibana:1.6.0
        env:
        - name: ELASTICSEARCH_URL
          value: https://elasticsearch:9200
        - name: ELASTICSEARCH_HOSTS
          value: https://elasticsearch:9200
        - name: SERVER_SSL_ENABLED
          value: "false"
        - name: SERVER_SSL_KEY
          value: /usr/share/kibana/config/kibana.key
        - name: SERVER_SSL_CERTIFICATE
          value: /usr/share/kibana/config/kibana.pem
        - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
          value: /usr/share/kibana/config/root-ca.pem
        - name: CLUSTER_NAME
          value: logs
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 1
            memory: 2Gi
#        readinessProbe:
#          tcpSocket:
#            port: http
#          initialDelaySeconds: 20
#          periodSeconds: 10
#        livenessProbe:
#          tcpSocket:
#            port: http
#          initialDelaySeconds: 20
#          periodSeconds: 10
        ports:
        - containerPort: 5601
          name: http
        volumeMounts:
        - mountPath: /usr/share/kibana/config/kibana.yml
          name: config
          subPath: kibana.yml
        - mountPath: /usr/share/kibana/config/kibana.pem
          name: certs
          subPath: kibana.pem
          readOnly: true
        - mountPath: /usr/share/kibana/config/kibana.key
          name: certs
          subPath: kibana.key
          readOnly: true
        - mountPath: /usr/share/kibana/config/root-ca.pem
          name: certs
          subPath: root-ca.pem
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: kibana
      - name: certs
        secret:
          secretName: kibana-tls-data
---
apiVersion: v1
kind: Secret
metadata:
  name: kibana-tls-data
  namespace: logging
type: Opaque
stringData:
  kibana.pem: |-
    -----BEGIN CERTIFICATE-----
    MIIDiTCCAnECFBlKl6PnIW7XtTuG5liI955df0DOMA0GCSqGSIb3DQEBCwUAMH0x
    CzAJBgNVBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRIwEAYDVQQHDAlQYWxv
    IEFsdG8xDzANBgNVBAoMBkhQIEluYzEdMBsGA1UECwwUSFAgQnVzaW5lc3MgUGxh
    dGZvcm0xFTATBgNVBAMMDEhQQlAgQ0EgUm9vdDAeFw0yMDA0MTAyMTM1MDJaFw0y
    MDA1MTAyMTM1MDJaMIGEMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5p
    YTESMBAGA1UEBwwJUGFsbyBBbHRvMQ8wDQYDVQQKDAZIUCBJbmMxHTAbBgNVBAsM
    FEhQIEJ1c2luZXNzIFBsYXRmb3JtMRwwGgYDVQQDDBNrYm5hLmRldm9wcy5ocGJw
    LmlvMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0Kb0er/l0B6iV2DI
    gn6cmAmeDqlofMjJvqn1KfsXXlTRl7QFrYf3wDEa8eIfJWWmTgpeItnQZfkpbVxo
    qy9yGIsl5kIDKCBThsFlJPOHk7J+mj6qVdqYqPrbtFrzCCD5e+ZrQ7Zn7ShiiHx2
    o3KyRFdXauOUrlnf5Q21f8Bxfj9IFf+kPUaCw/PyCNIkwTq2Tww2rizLT5LNbRws
    IPbZ5ufSXk7Uwzo8lvZdu5fjnobDAEKZx0TGl1VycUflZ7L1t/1vbQ6XmL7i5eym
    HabVrF/xLfyLxzB+6FdwLD8cinNBo+MuLfnHJwAkwjJV2jEE31sRRmE/JH4o2M1A
    8g5PuQIDAQABMA0GCSqGSIb3DQEBCwUAA4IBAQCFXCB0H9spy7bAC8NOJk2bBxCW
    H35QsYIl96EELMM7Rd1VeEaxat1Q/Py5xPecs9KsCY36+pNAfp/S1y8S/rTSsXgx
    L9rlj9uFXVRcWshoywp2tFLW5l2uaukQgDtRsypL6nMzRzJOkVKToOdKTLqSKvye
    Shk4GPh/3yR4WGEHozBQR6p+6GFgOU27lMEESv+uSvaqXuyD3nMNjhGdzMEoEMOJ
    JtGv8avk9c+ZlILAYtp84DWk8lY2zdgs4YQhYmXatem1va76y3tGLMcBraSD1bSm
    3Tb5N0d6pBMzJQi/FwVBNJnRzdTd6NKumZrKhxHtzEZD4LZAcChUdz2Yb/en
    -----END CERTIFICATE-----
  kibana.key: |-
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDYkxPUsCo8+m/S
    eTmluM+M3no9L6shltkNx6Ha8jZeb7qSXXUtbbVO1sVRwQJbGN3mQf+Ld3ZnM+XP
    DsA6H+X3A4gSJlN1oLyNNw6x08U6DtXN/fa2qycpDnuk5Qbc/INzFi5kab+QIcz2
    24uE9+iR6uBxlhz6Jg8y5wsFpB3T3XmveQ+7uYFTMEqNutjQgJea3muWxdm+UMr/
    7PcmRYE2DJfuMDIySvBpQb8JfrDVT4g6PbhOus/7vMyFrNACsnrvJpfoV1ATcJuz
    4IyCso9uhn0JyDD6DXGPBVBhXfZjHdY4iqdVragTCLIp1E1Bb5K67ra8WL7CdWBL
    iezfHihFAgMBAAECggEAZpGRbMNZ3bNFzkp3UNMsCK08+0leJPRKK8qGDylzMlp7
    4+G7Ix64JXR10vgz42zteqV7H1QekVX02pFD3MNKqCfWA7J/CFBtu/t9TB7dY1ev
    TnWeqHh6fWlMiZWmIHa+0nyI0Cl8/gfkCG2FsB2w2ZqBXYoYgygPPq5JfAxzy+hS
    jynY67KjHUbOG1hsziKjmSbMYiE/3lTlFGA2Rts5VmKmRMrf03lJlzGF/+UFChwT
    sj4V98dnx3UfYX+IBZYuidgasS/e8e+wvPIvJF0kom7OkiVvIur/2ZK3ev/QgYS/
    iSlfEnAhtS1XeoHEF/MqR4F/XMvxOMYWll8Zp54UaQKBgQD+NwPOk0/k3Wwvf4/B
    PGVvBf8iAm9jNUCq8UJRt2R/R3CMNyL1vw4KhjmSiOAJrxNPobtHHSxBo8brFpE0
    F2gOxhKvUTaTDC8XQjhetzTiUgdNOVpclOsfYaKeG9QD1r2gSODuZBM2LWoRLSbb
    gpzRuQTm1VPzPf4TiDsI4Wts7wKBgQDaGGYkwXLgC2J0enngFOklJvCxxsTN3kIQ
    LYDXF+7hBqTqSE4kdlR2PRLrWS+k7fmYgBS1q1F96BPpqQzqSC1wKzNP9aURRkgT
    wVMXnq+I/SBPfrVP9ocjPeBz1kNmBnOiWRjrX5JT5YdMWQcgq5yUWPbNwWnuZn+m
    7P7zgfsmCwKBgQC0p4n4Cm3TWZshIgiZrP70aBGILKzVlqlvEWYsxiQP40fTDPe2
    JeCnj/1n6gc0OouBopCBF/U0bFvXAsGLgDq9jPsIRbF/zD/GypNek9lsIBj6QxC5
    DEcOlQbIT0Raugcl2cSnBM02Sg2/SRP9GJOy4kXeeKlhCaP+Y2h4hiEeVwKBgQDB
    g0CugE8TaEaVn06gey1bX6/Vrc5V9E2d2SImt/+m/qQ5lKpxQ+UxfINa+6mAp/79
    RzgY8ce+9bslanAhOKXIjyxaWFV8fGXb0X+Ox6hs3lxa7MyoBNBnfrG3Vng7AKJ9
    fJzVy9kkQ9bG8X+Xh23JWx6x9lmtxJijXknheoWDfQKBgDyRxmYXDYrXpCgrwYjU
    4lAyARf/LfImSoUbYJybhBaNUL6neEBWTBbY4mNHcyLYjjjfo3PFkEhKfNo7BP17
    XW6uQAQJYunVpCMzFvSyG1ElpOL2QXMjVfzIY5Uv7XcbmTVAVirHzs7WqiFcCLgO
    ozBn9ETunIV/2jEMFgqvx0++
    -----END PRIVATE KEY-----
  root-ca.pem: |-
    -----BEGIN CERTIFICATE-----
    MIID2zCCAsOgAwIBAgIUb178BSAu1LUZTKjRcPLrQ9ovcTswDQYJKoZIhvcNAQEL
    BQAwfTELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExEjAQBgNVBAcM
    CVBhbG8gQWx0bzEPMA0GA1UECgwGSFAgSW5jMR0wGwYDVQQLDBRIUCBCdXNpbmVz
    cyBQbGF0Zm9ybTEVMBMGA1UEAwwMSFBCUCBDQSBSb290MB4XDTIwMDQwMjIzMDQy
    OFoXDTIwMDUwMjIzMDQyOFowfTELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlm
    b3JuaWExEjAQBgNVBAcMCVBhbG8gQWx0bzEPMA0GA1UECgwGSFAgSW5jMR0wGwYD
    VQQLDBRIUCBCdXNpbmVzcyBQbGF0Zm9ybTEVMBMGA1UEAwwMSFBCUCBDQSBSb290
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxnMF7rHdZl6ykWKRoYVC
    /3kkD5mCHsogJyZ+stVUJnz0vqiaTJfadvJyM42fhxQ69NvkvHdqY0dfezbut/WQ
    AqrKSzXFpu6VRJcSxC8KDz782L6Eed/V78hl2UGMEs8vJZh5wGrXrKFE8t7+BAld
    lnGsmDGMa4idJRgZoEheGnFBcu4mKCr2IWwcLiX/MlXWqbYoCOwIw40EqULFcDMq
    OyiGeImWrkQ6hb4i2GaLgXNjH8sLfPh6uxc6k/mA/LqQywFvCnPQbhW2KTL4oK8B
    umTGm2tCYp+buPw9vJwCc9VHbpom4JZQf3uLUEteJSuAkkhhqz6JaoscUors7eC7
    NQIDAQABo1MwUTAdBgNVHQ4EFgQUbIFdFJCqNct0vPX1Ojs11qFqlnowHwYDVR0j
    BBgwFoAUbIFdFJCqNct0vPX1Ojs11qFqlnowDwYDVR0TAQH/BAUwAwEB/zANBgkq
    hkiG9w0BAQsFAAOCAQEAbOEEBmi1BeatTGVmrMF/v8sfrAwg5PaehlGl83q4SFsj
    ksxBTAe9rJDNepThjdTpVL5sczN4iz1ZUB83TjhJMNARTqkM/P2f8amKkaN5pd7f
    K14ts1Ev39qk8x+9uEchMsR4UPr4kST1z1D5fdgk/sydByB3G4EPLNDuXxhbjIJS
    t6w5fEa6WaUOLJAo2zYI3DUyGWG7D2VMEoY2RCOwUpwvn6gfkeW6VKGx4wZN/uMJ
    4iU/TND6DPX+D3p4RPuQWhPbZvHbLmiPNDWyC8pmhtJIbrEV0ed9vPYmMTxT/dZZ
    k8graZg6R13aFdFgaCy7Ah+vKBBLgCv+YLYhKCtEPQ==
    -----END CERTIFICATE-----
  keycloak-ca.pem: |-
    -----BEGIN CERTIFICATE-----
    MIIFKzCCAxMCFEMeGuX1NP2jx7v8Mx/QutUfklgBMA0GCSqGSIb3DQEBCwUAMFIx
    EDAOBgNVBAMMB3Jvb3QtY2ExCzAJBgNVBAYTAlVTMQ0wCwYDVQQKDARQU1NXMQ0w
    CwYDVQQLDARIUEJQMRMwEQYDVQQIDApDYWxpZm9ybmlhMB4XDTIwMDUxOTIzMjUx
    N1oXDTIyMDUxOTIzMjUxN1owUjEQMA4GA1UEAwwHcm9vdC1jYTELMAkGA1UEBhMC
    VVMxDTALBgNVBAoMBFBTU1cxDTALBgNVBAsMBEhQQlAxEzARBgNVBAgMCkNhbGlm
    b3JuaWEwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCvEAxYcl6QheYd
    9exW75u5ZUF1JE8ApFxlQ09Gv01RpxXHqLDNt/pPnTch5ht4HdkR9Sl7P9nb3Dec
    oQkzd7CkEFWmMzYd/Op+VbuqmYKNyqzMl/FdVBB3tNz1no3GZ/E8UN6S4n5tbA40
    X0oU+B7dg5YLbMgfid9VOhlYpxx2xG0j1BDCG1Z+OGzaTnfBk04OU6NPoYIxUQ1k
    Klpzx0+19kPsxf0SgUekc+xoR1IDslg2Gq0R75WEteXe3L64TfdPKQaaYYxsJ9M6
    Y8BULbexW5qd43LcpA2nLCCDnFOKFsuOiLULKAxqxu+aErdvYIGYPI0+hF7bsos6
    0jjGURLZFS9Z0hXP7Qq1+nKebvAvd/DHJejH3w0NGIbPG70W+UAmi46ljj4oBFOK
    pnqH7q7IjRgQNcd3hgYQLAynkko8C6haS6kG39Jlnh3slRZ/FJjO09OEtILmQF1D
    eQoM1tu/5rr5hF6h8KFiSwQPiS8XbuAxF15KbQUpfSkfauLVMPTROJximrS0UJAU
    CI8P4NJ/QqsPY9DfnuUaDbk2DOqLQ8EcFYdd4KZ61DeDCBD7jNlqdwc4AUfnnqcO
    gkg3V5+hv1kxF/2wLmvBnvCOVmo7KRzgiq2HnU8TkXu7xdBL7+ywQX/Mu0pGvajy
    vjVN0qEy2dHlQ0H279DrH74KMG6KsQIDAQABMA0GCSqGSIb3DQEBCwUAA4ICAQBk
    d83BmXoznvVzQTv2UdVazoFcF/4S0o1O5bQYnoHIyZV7AI7dZE5CmTd6x9k6uCf8
    fJbOtD+TiWx7vJY7gV4TsIpA6jMJ09IlVp7Mra6yDu6f07ubwSdHitmvJnt+eqF7
    TVoxJ8oH//b1nlFJr64x9i6NoL185O0bfMTG46ff/Xl4Ldwto/qiRtS6EvP+eedO
    I8MrpD+pM+QnW2qpYI2ogFy+KhxJD+fb3RKuFjPBQ7KKO5GwTTnv9iG4IHqHeI3B
    TfcyTrKutmqO62m6dg1svrF0ZUW8wmAo5aD7Ulf3nxqzo1v3mLqYM6y/t1mTwTls
    J6rbAnttbuP3gF2WyOwGbE9rBZrcS7DVoTzXEDGZuGz5DnsOfpJGgkMN7OvoLmx1
    xhszZlX/M4Y7Z2mZ0AQmqg5EgtgEecR6JvFQ0kWKN5juBDdzr3hNYaCW1va1Jnqa
    EJOJZimxi3JEnWyRRaNwwaU/6VA3Ob2NVY8tL/zH7lVXf8jHcbILbcdyVjLKwkdc
    c7NaRQwRhUoR7CQknubiE5VLJQzcWMnFH6FXPFvlFm8XBJQVEputOtWCRGVFUqfv
    n5CSiw+bp6zQmmL2k7jyPXNbtrTs42NMXROO2NAM03RwmGox8MsCjkUziGdz8aTK
    vBvKtXoWQzDbkrWgs+dS+WWq3V5G2jiYojR3gBn0pw==
    -----END CERTIFICATE-----
