---
kind: Service
apiVersion: v1
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerSourceRanges:
    - 15.0.0.0/9
    - 192.56.0.0/16
    - 76.126.85.105/32
  selector:
    component: kibana
  ports:
  - name: http
    port: 5601
    targetPort: 5601