# iceadmin, P0aGHl04c6pPxA==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: logging
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
     app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image:  quay.io/keycloak/keycloak:latest
        env:
        - name: DB_VENDOR
          value: postgres
        - name: DB_ADDR
          value: postgres
        - name: DB_DATABASE
          valueFrom: 
            secretKeyRef:
              name: postgres
              key: postgres_db
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres
              key: postgres_user
        - name: DB_SCHEMA
          value: public
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: postgres_pwd
        - name: KEYCLOAK_USER
          value: iceadmin
        - name: KEYCLOAK_PASSWORD
          value: P0aGHl04c6pPxA==
#        - name: PROXY_ADDRESS_FORWARDING
#          value: "true"
        ports:
        - name: web
          containerPort: 8080
