version: '3.2'
services:
  node1:
    image: amazon/opendistro-for-elasticsearch:1.6.0
    container_name: node1
    hostname: node1
    domainname: mylab.local
    environment:
      - cluster.name=es-cluster
      - node.name=node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - bootstrap.system_call_filter=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the Elasticsearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - "data1:/usr/share/elasticsearch/data"
      - "./sysctl/elastic.conf:/etc/sysctl.d/elastic.conf"
      - "./esconfig/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./esconfig/log4j2.properties.debug:/usr/share/elasticsearch/config/log4j2.properties"
      - "./ssl/aws/root-ca.pem:/usr/share/elasticsearch/config/root-ca.pem:ro"
      - "./ssl/aws/node1.pem:/usr/share/elasticsearch/config/node.pem:ro"
      - "./ssl/aws/node1.key:/usr/share/elasticsearch/config/node.key:ro"
      - "./ssl/aws/root-ca.pem:/usr/share/elasticsearch/config/admin-root-ca.pem:ro"
      - "./ssl/aws/admin.pem:/usr/share/elasticsearch/config/admin.pem:ro"
      - "./ssl/aws/admin.key:/usr/share/elasticsearch/config/admin.key:ro"
# Security Plugin configuration
      - "./security/config.yml.auth0:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/config.yml"
#      - "./security/action_groups.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/action_groups.yml"
#      - "./security/internal_users.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml"
      - "./security/roles.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles.yml"
      - "./security/roles_mapping.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles_mapping.yml"
#      - "./security/tenants.yml:/usr/share/elasticsearch/plugins/opendistro_security/securityconfig/tenants.yml"
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es-net

  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:1.6.0
    container_name: kibana
    hostname: kibana
    domainname: mylab.local
    volumes:
      - "./kiconfig/kibana.yml.auth0:/usr/share/kibana/config/kibana.yml"
      - "./ssl/aws/kibana.pem:/usr/share/kibana/config/kibana.pem:ro"
      - "./ssl/aws/kibana.key:/usr/share/kibana/config/kibana.key:ro"
      - "./ssl/aws/root-ca.pem:/usr/share/kibana/config/root-ca.pem:ro"
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      CLUSTER_NAME: es-cluster
      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_KEY: /usr/share/kibana/config/kibana.key
      SERVER_SSL_CERTIFICATE: /usr/share/kibana/config/kibana.pem
    networks:
      - es-net
volumes:
  data1:
networks:
  es-net:
