---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecr-access-watcher
  namespace: logging
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ecr-access-watcher
subjects:
  - kind: ServiceAccount
    name: ecr-access-watcher
    namespace: logging
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
