apiVersion: logging.banzaicloud.io/v1beta1
kind: Logging
metadata:
  name: logging-cn
spec:
  fluentd:
    scaling:
      replicas: 3
  fluentbit:
    image:
      pullPolicy: IfNotPresent
      repository: fluent/fluent-bit
      tag: 1.4.2
  controlNamespace: logging

