---
apiVersion: v1
data:
  password: cURMNUdiSGNUOHBtMFFJUkQyWTZB
  username: YWRtaW4=
kind: Secret
metadata:
  name: es-secrets
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: cluster-hpbp
  namespace: logging
spec:
  elasticsearch:
    host: elasticsearch.logging.svc.cluster.local
    port: 9200
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    user: admin
    password:
      valueFrom:
        secretKeyRef:
          name: es-secrets
          key: password
    index_name: hpbp-tenant
    buffer:
      timekey: 1m
      timekey_wait: 30s
      timekey_use_utc: true
      retry_forever: false
      retry_max_times: 3
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: cluster-flow-hpbp
  namespace: logging
spec:
  match:
    - select:
        namespaces:
          - hpbp-dev-core 
          - hpbp-dev-default 
          - hpbp-qa-default
  filters:
    - tag_normaliser: 
        format: ${namespace_name}.${pod_name}.${container_name}
    - parser:
        remove_key_name_field: true
        reserve_data: true
        parse:
          type: none
  outputRefs:
    - cluster-hpbp