---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
  name: keycloak-backup
  namespace: logging
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: arn:aws:iam::198814579854:role/auth-dev-backup-s3
        spec:
          imagePullSecrets:
            - name: ecr-pull-core
          volumes:
           - name: pg-data
             emptyDir: {}
          containers:
          - name: pg-backup
            image: 198814579854.dkr.ecr.us-east-1.amazonaws.com/devops/pg_utils:1.0.5
            command: ["/bin/sh", "-c", "/home/user/dumpDatabase.sh"]
            volumeMounts:
             - name: pg-data
               mountPath: "/home/user/pg_backup"
            env:
             - name: S3_BUCKET
               value: auth-dev-backup
             - name: PGHOST
               value: "postgres.logging.svc.cluster.local"
             - name: PGPORT
               value: "5432"
             - name: PGDATABASE
               valueFrom:
                 secretKeyRef:
                   name: postgres
                   key: postgres_db
             - name: PGUSER
               valueFrom:
                 secretKeyRef:
                   name: postgres
                   key: postgres_user
             - name: PGPASSWORD
               valueFrom:
                 secretKeyRef:
                   name: postgres
                   key: postgres_pwd
          dnsPolicy: ClusterFirstWithHostNet
          hostNetwork: true
          restartPolicy: Never
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
  schedule: 0 0 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
