---
apiVersion: v1
data:
  password: cURMNUdiSGNUOHBtMFFJUkQyWTZB
  username: YWRtaW4=
kind: Secret
metadata:
  name: es-secrets
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: output-shared
spec:
  elasticsearch:
    host: elasticsearch.logging.svc.cluster.local
    port: 9200
    scheme: https
    ssl_verify: false
    ssl_version: TLSv1_2
    include_timestamp: true
    user: admin
    password:
      valueFrom:
        secretKeyRef:
          name: es-secrets
          key: password
    index_name: shared
    buffer:
      timekey: 20m
      timekey_wait: 30s
      timekey_use_utc: true
      retry_forever: false
      retry_max_times: 5
---
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: flow-1
spec:
  match:
    - exclude:
        labels:
          tenant: customer2
    - select: {}

  filters:
    - stdout:
        output_type: json
    - tag_normaliser: 
        format: ${namespace_name}.${pod_name}.${container_name}
    - parser:
        remove_key_name_field: true
        reserve_data: true
        parse:
          type: apache2
  outputRefs:
    - output-shared
#---
#apiVersion: logging.banzaicloud.io/v1beta1
#kind: Flow
#metadata:
#  name: flow-1
#spec:
#  match:
#    - select:
#        labels:
#          tenant: customer1
#  filters:
#    - stdout:
#        output_type: json
#    - tag_normaliser: 
#        format: ${namespace_name}.${pod_name}.${container_name}
#    - parser:
#        remove_key_name_field: true
#        reserve_data: true
#        parse:
#          type: apache2
#  outputRefs:
#    - output-shared
#---
#apiVersion: logging.banzaicloud.io/v1beta1
#kind: Flow
#metadata:
#  name: flow-3
#spec:
#  match:
#    - select:
#        labels:
#          tenant: customer3
#  filters:
#    - stdout:
#        output_type: json
#    - tag_normaliser: 
#        format: ${namespace_name}.${pod_name}.${container_name}
#    - parser:
#        remove_key_name_field: true
#        reserve_data: true
#        parse:
#          type: apache2
#  outputRefs:
#    - output-shared
